spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/all?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

# 配置freemarker模板引擎
  freemarker:
    prefix: /ftl/
    suffix: .ftl

# redis
  redis:
    # 数据库索引（默认为0）
    database: 0
    # 服务器地址ip
    host: 127.0.0.1
    # 服务器连接端口
    port: 6379
    # 服务器连接密码（默认为空）
    password:
    jedis:
      pool:
    # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000ms





#  控制台打印sql语句（mybatis）
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  控制台打印sql语句（日志）
logging:
  level:
    com.ws.all.bean.mapper: trace
    com.ws.all.service: trace

# mybatis xml扫描路径
mybatis:
  mapper-locations: classpath:mapper/*.xml







